FROM python:3.8-slim-buster

RUN  apt-get update \
  && apt-get install -y wget 

WORKDIR /app
COPY . /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

ENTRYPOINT ["python"]
CMD ["app.py"]
